import PDFDocument from 'pdfkit';

function asText(v) {
  if (v === null || v === undefined) return '';
  if (typeof v === 'string') return v;
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  try {
    return JSON.stringify(v);
  } catch {
    return String(v);
  }
}

function labelize(key) {
  return String(key || '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (m) => m.toUpperCase());
}

async function docToBuffer(doc) {
  const chunks = [];
  return await new Promise((resolve, reject) => {
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

export async function generateClientOnboardingPdf({ payload }) {
  const user = payload?.user || {};
  const profile = payload?.profile || {};
  const brand = payload?.brand || {};
  const services = Array.isArray(payload?.services) ? payload.services : [];

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: 'Client Onboarding — Completed',
      Author: 'Anchor',
      Creator: 'Anchor Dashboard'
    }
  });

  // Header
  doc.fontSize(22).font('Helvetica-Bold').text('Client Onboarding — Completed', { align: 'center' });
  doc.moveDown(0.25);
  doc.fontSize(10).font('Helvetica').fillColor('#666666').text(new Date().toLocaleString(), { align: 'center' });
  doc.fillColor('#000000');
  doc.moveDown(1.25);

  const sectionTitle = (t) => {
    doc.moveDown(0.75);
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#111827').text(t);
    doc.moveDown(0.35);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e5e7eb');
    doc.moveDown(0.65);
    doc.fillColor('#111827').font('Helvetica');
  };

  const kv = (k, v) => {
    const label = String(k);
    const val = asText(v) || '—';
    const startY = doc.y;
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text(`${label}:`, 50, startY, { width: 160 });
    doc.fontSize(10).font('Helvetica').fillColor('#111827').text(val, 220, startY, { width: 325 });
    const h = Math.max(doc.heightOfString(val, { width: 325 }), 12);
    doc.y = startY + h + 6;
  };

  sectionTitle('Account');
  kv('Email', user.email);
  kv('Client Name', [user.first_name, user.last_name].filter(Boolean).join(' ').trim());

  sectionTitle('Profile');
  kv('Display Name', profile.display_name || '');
  kv('Call Tracking Main Number', profile.call_tracking_main_number || '');
  kv('Front Desk Emails', profile.front_desk_emails || '');
  kv('Office Admin Name', profile.office_admin_name || '');
  kv('Office Admin Email', profile.office_admin_email || '');
  kv('Office Admin Phone', profile.office_admin_phone || '');
  kv('Form Email Recipients', profile.form_email_recipients || '');

  sectionTitle('Brand');
  kv('Business Name', brand.business_name || '');
  kv('Website URL', brand.website_url || '');
  kv('Business Description', brand.business_description || '');
  kv('Brand Notes', brand.brand_notes || '');

  const logos = Array.isArray(brand.logos) ? brand.logos : [];
  if (logos.length) {
    kv(
      'Uploaded Files',
      logos
        .map((a) => {
          const kind = a?.kind ? `(${a.kind}) ` : '';
          return `${kind}${a?.name || a?.url || ''}`.trim();
        })
        .filter(Boolean)
        .join('\n')
    );
  }

  sectionTitle('Access & Integrations');
  const accessKeys = [
    'website_access_status',
    'ga4_access_status',
    'google_ads_access_status',
    'meta_access_status',
    'website_forms_details_status',
    'website_forms_notes'
  ];
  accessKeys.forEach((k) => kv(labelize(k), profile[k] || ''));

  sectionTitle('Services');
  if (!services.length) {
    kv('Services', '—');
  } else {
    const lines = services
      .map((s) => {
        const active = s?.active === false ? ' (inactive)' : '';
        return `- ${s?.name || '(unnamed)'}${active}`;
      })
      .join('\n');
    kv('Selected Services', lines);
  }

  // Type-specific questionnaire responses
  const questionnaire = profile?.onboarding_questionnaire || {};
  const questionnaireKeys = Object.keys(questionnaire).filter((k) => {
    const val = questionnaire[k];
    if (val === null || val === undefined || val === '') return false;
    if (Array.isArray(val) && val.length === 0) return false;
    return true;
  });

  if (questionnaireKeys.length > 0) {
    sectionTitle('Market Research & SEO Intake');
    questionnaireKeys.forEach((key) => {
      const val = questionnaire[key];
      const displayVal = Array.isArray(val) ? val.join(', ') : asText(val);
      kv(labelize(key), displayVal);
    });
  }

  // Footer
  doc.moveDown(1.25);
  doc.fontSize(8).fillColor('#6b7280').text('Generated by Anchor • Please retain for your records.', {
    align: 'center'
  });

  const buffer = await docToBuffer(doc);
  const safeEmail = String(user.email || 'client').replace(/[^a-z0-9]+/gi, '_').toLowerCase();
  const filename = `anchor_onboarding_${safeEmail}_${Date.now()}.pdf`;
  return { buffer, filename };
}


